from typing import Any

from pypi_types.pep440_rs import Version
from pypi_types.pypi_releases import File

def filename_to_version(*args, **kwargs) -> Any: ...
def parse_releases_data(*args, **kwargs) -> Any: ...
def collect_extras(*args, **kwargs) -> Any: ...
def read_parsed_release_data(data: bytes) -> dict[Version, list[File]]: ...
def write_parsed_release_data(data: dict[Version, list[File]]) -> str: ...
